# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'k8s lock'
description: 'Protect steps in your workflow from concurrent execution using a kubernetes secret to implement a distributed lock'
author: 'mgalgs'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  kube_config_data:
    description: 'base64 encoded kubeconfig (generally from a secret). The "aws" command is available (aws-cli-v2)'
    required: true
  kube_context:
    description: 'The context from the provided kubeconfig that should be used (will be passed to kubectl use-context)'
    required: false
  lock_name:
    description: "Lock name (should be unique across all actions in this repo)."
    required: true
  max_attempts:
    description: "How many times locking will be attempted before bailing out."
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/main.sh'
  post-entrypoint: '/post.sh'
